version: '3'

services:
  php:
    container_name: php
    image: php:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
