version: '3'

services:
  php:
    container_name: php
    image: php:latest
    build: .
    volumes:
      - .:/var/www

  nginx:
    image: nginx:latest
    build: ./docker/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www
    depends_on:
      - php
