version: '3'

services:
  app:
    container_name: app
    build:
      context: .docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      APP_NAME: 'GearLab'
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      APP_SCHEME: 'http'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: 'laravel_development'
      DB_DATABASE_TEST: 'laravel_testing'
      DB_USERNAME: 'docker'
      DB_PASSWORD: 'docker'
    volumes:
      - .:/app
    expose:
      - 9000
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - app
  db:
    image: postgres:12
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'laravel_development'
    volumes:
      - database:/var/lib/postgresql/data
      - .docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

networks:
  default:
    name: gearlab
volumes:
  database:
