on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS on Staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
      
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 # default
          verbose: false # default
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Composer install
      - uses: php-actions/composer@v5
        with:
          php_version: 7.3
          progress: yes
          version: latest
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR # ECRイメージPush
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}

        run: |
          echo $ECR_REPOSITORY
          IMAGE_TAG=latest
          docker build -t 499506883380.dkr.ecr.ap-northeast-1.amazonaws.com/php:latest .
          docker push 499506883380.dkr.ecr.ap-northeast-1.amazonaws.com/php:latest
