<?php

namespace Tests\Feature\Controllers;

use App\Models\Gear;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use Laravel\Dusk\Browser;

class AdminControllerTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_admin_access()
    {
        $response = $this->get('admin');

        $response->assertStatus(302);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_adminLogin()
    {
        $response = $this->get('admin/login');
//
//        $this->browse(function ($first, $second) {
//            $first->loginAs(User::find(1))
//                ->visit('/home');
//        });
//        $this -> visit('admin/login')
//            ->type('admin', 'user_id')
//            ->type('admin', 'password')
//            ->press('ログイン')
//            ->seePageIs('/admin');
//        $response->assertStatus(200);
    }
}
