<?php

namespace Tests\Feature\Controllers;

use App\Models\Gear;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use function PHPUnit\Framework\assertSame;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class GearApiControllerTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        //データベースマイグレーション
        $this->artisan('migrate');

    }

    /**
     * A basic feature test example.
     *
     * @test index
     */
    public function APIでGear一覧を取得する()
    {
//        連結テスト

        //データは0であること確認
        $this->assertEquals(0, Gear::all()->count());

        //データの準備
        $gear1 = Gear::factory()->create();
        $gear2 = Gear::factory()->create();
        //データのpost
        $this->post('api/gears', $data = [$gear1, $gear2]);
        //データ取得
        $gear = Gear::all();
        $this->get('api/gears')->assertOk();
        //データプラスされていることを検証
        $this->assertEquals(2, Gear::all()->count());

    }

    /**
     * A basic feature test example.
     *
     * @test post
     */
    public function APIでGearを登録する()
    {
        //データ保存する準備
        $gear1 = Gear::factory()->create();
        $gear2 = Gear::factory()->create();

        $this->post('api/gears', $data = [$gear1, $gear2]);
        //検証
        $this->assertEquals(2, Gear::all()->count());

    }


}
